### PR TITLE
refactor: yarn lock file

### PR DESCRIPTION
**Pull request by ssk090**
### PR Fixes:
-  Refactoring the yarn file.
image
image

for more detaills: https://www.npmjs.com/package/yarn-deduplicate
check this 

Resolves #[Issue Number if there] 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by ssk090** [comment]
accept all the incoming changes for the PR or try out this command: `npx yarn-deduplicate yarn.lock` on top of your changes @rohithreddy009

**Comment by rohithreddy009** [comment]
On it

**Comment by rohithreddy009** [comment]
> accept all the incoming changes for the PR or try out this command: `npx yarn-deduplicate yarn.lock` on top of your changes @rohithreddy009

having merge conflicts in the pr, could you fix it

**Comment by rohithreddy009** [comment]
> accept all the incoming changes for the PR or try out this command: `npx yarn-deduplicate yarn.lock` on top of your changes @rohithreddy009

pr having merge conflicts,I need to talk on this issue
can you connect on discord ?

**Comment by ssk090** [comment]
> > accept all the incoming changes for the PR or try out this command: `npx yarn-deduplicate yarn.lock` on top of your changes @rohithreddy009
> 
> pr having merge conflicts,I need to talk on this issue can you connect on discord ?

yeah sure
discord id: shivananda.sai

**Pull request closed without merging**
